# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PanpalDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'HWPanModal'
  pod 'SnapKit'

  # Pods for PanpalDemo

  target 'PanpalDemoTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'PanpalDemoUITests' do
    # Pods for testing
  end

end
