var annotated_dup =
[
    [ "<MAAnnotation >", "protocol_m_a_annotation_01-p.html", "protocol_m_a_annotation_01-p" ],
    [ "MAAnnotationView", "interface_m_a_annotation_view.html", "interface_m_a_annotation_view" ],
    [ "MACircle", "interface_m_a_circle.html", "interface_m_a_circle" ],
    [ "MACircleRenderer", "interface_m_a_circle_renderer.html", "interface_m_a_circle_renderer" ],
    [ "MACircleView", "interface_m_a_circle_view.html", "interface_m_a_circle_view" ],
    [ "MACoordinateBounds", "struct_m_a_coordinate_bounds.html", "struct_m_a_coordinate_bounds" ],
    [ "MACoordinateRegion", "struct_m_a_coordinate_region.html", "struct_m_a_coordinate_region" ],
    [ "MACoordinateSpan", "struct_m_a_coordinate_span.html", "struct_m_a_coordinate_span" ],
    [ "MAGeodesicPolyline", "interface_m_a_geodesic_polyline.html", null ],
    [ "MAGroundOverlay", "interface_m_a_ground_overlay.html", "interface_m_a_ground_overlay" ],
    [ "MAGroundOverlayRenderer", "interface_m_a_ground_overlay_renderer.html", "interface_m_a_ground_overlay_renderer" ],
    [ "MAGroundOverlayView", "interface_m_a_ground_overlay_view.html", "interface_m_a_ground_overlay_view" ],
    [ "MAHeatMapGradient", "interface_m_a_heat_map_gradient.html", "interface_m_a_heat_map_gradient" ],
    [ "MAHeatMapNode", "interface_m_a_heat_map_node.html", "interface_m_a_heat_map_node" ],
    [ "MAHeatMapTileOverlay", "interface_m_a_heat_map_tile_overlay.html", "interface_m_a_heat_map_tile_overlay" ],
    [ "MAMapPoint", "struct_m_a_map_point.html", "struct_m_a_map_point" ],
    [ "MAMapRect", "struct_m_a_map_rect.html", "struct_m_a_map_rect" ],
    [ "MAMapSize", "struct_m_a_map_size.html", "struct_m_a_map_size" ],
    [ "MAMapView", "interface_m_a_map_view.html", "interface_m_a_map_view" ],
    [ "MAMapView(LocationOption)", "category_m_a_map_view_07_location_option_08.html", "category_m_a_map_view_07_location_option_08" ],
    [ "MAMapView(Snapshot)", "category_m_a_map_view_07_snapshot_08.html", "category_m_a_map_view_07_snapshot_08" ],
    [ "<MAMapViewDelegate >", "protocol_m_a_map_view_delegate_01-p.html", "protocol_m_a_map_view_delegate_01-p" ],
    [ "MAMultiColoredPolylineRenderer", "interface_m_a_multi_colored_polyline_renderer.html", "interface_m_a_multi_colored_polyline_renderer" ],
    [ "MAMultiPoint", "interface_m_a_multi_point.html", "interface_m_a_multi_point" ],
    [ "MAMultiPolyline", "interface_m_a_multi_polyline.html", "interface_m_a_multi_polyline" ],
    [ "<MAOverlay >", "protocol_m_a_overlay_01-p.html", "protocol_m_a_overlay_01-p" ],
    [ "MAOverlayPathRenderer", "interface_m_a_overlay_path_renderer.html", "interface_m_a_overlay_path_renderer" ],
    [ "MAOverlayPathView", "interface_m_a_overlay_path_view.html", "interface_m_a_overlay_path_view" ],
    [ "MAOverlayRenderer", "interface_m_a_overlay_renderer.html", "interface_m_a_overlay_renderer" ],
    [ "MAOverlayView", "interface_m_a_overlay_view.html", "interface_m_a_overlay_view" ],
    [ "MAPinAnnotationView", "interface_m_a_pin_annotation_view.html", "interface_m_a_pin_annotation_view" ],
    [ "MAPointAnnotation", "interface_m_a_point_annotation.html", "interface_m_a_point_annotation" ],
    [ "MAPolygon", "interface_m_a_polygon.html", "interface_m_a_polygon" ],
    [ "MAPolygonRenderer", "interface_m_a_polygon_renderer.html", "interface_m_a_polygon_renderer" ],
    [ "MAPolygonView", "interface_m_a_polygon_view.html", "interface_m_a_polygon_view" ],
    [ "MAPolyline", "interface_m_a_polyline.html", null ],
    [ "MAPolylineRenderer", "interface_m_a_polyline_renderer.html", "interface_m_a_polyline_renderer" ],
    [ "MAPolylineView", "interface_m_a_polyline_view.html", "interface_m_a_polyline_view" ],
    [ "MAShape", "interface_m_a_shape.html", "interface_m_a_shape" ],
    [ "MATileOverlay", "interface_m_a_tile_overlay.html", "interface_m_a_tile_overlay" ],
    [ "MATileOverlay(CustomLoading)", "category_m_a_tile_overlay_07_custom_loading_08.html", "category_m_a_tile_overlay_07_custom_loading_08" ],
    [ "MATileOverlayPath", "struct_m_a_tile_overlay_path.html", "struct_m_a_tile_overlay_path" ],
    [ "MATileOverlayRenderer", "interface_m_a_tile_overlay_renderer.html", "interface_m_a_tile_overlay_renderer" ],
    [ "MATileOverlayView", "interface_m_a_tile_overlay_view.html", "interface_m_a_tile_overlay_view" ],
    [ "MAUserLocation", "interface_m_a_user_location.html", "interface_m_a_user_location" ],
    [ "MAUserLocationRepresentation", "interface_m_a_user_location_representation.html", "interface_m_a_user_location_representation" ],
    [ "NSValue(NSValueMAGeometryExtensions)", "category_n_s_value_07_n_s_value_m_a_geometry_extensions_08.html", "category_n_s_value_07_n_s_value_m_a_geometry_extensions_08" ]
];