# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChartsDemo
  
  pod 'Charts' # 图表
  pod 'TinyConstraints' # 约束

  target 'ChartsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartsDemoUITests' do
    # Pods for testing
  end

end
