var annotated_dup =
[
    [ "<MAAnimatableAnnotation >", "protocol_m_a_animatable_annotation_01-p.html", "protocol_m_a_animatable_annotation_01-p" ],
    [ "MAAnimatedAnnotation", "interface_m_a_animated_annotation.html", "interface_m_a_animated_annotation" ],
    [ "<MAAnnotation >", "protocol_m_a_annotation_01-p.html", "protocol_m_a_annotation_01-p" ],
    [ "MAAnnotationMoveAnimation", "interface_m_a_annotation_move_animation.html", "interface_m_a_annotation_move_animation" ],
    [ "MAAnnotationView", "interface_m_a_annotation_view.html", "interface_m_a_annotation_view" ],
    [ "MAArc", "interface_m_a_arc.html", "interface_m_a_arc" ],
    [ "MAArcRenderer", "interface_m_a_arc_renderer.html", "interface_m_a_arc_renderer" ],
    [ "MACircle", "interface_m_a_circle.html", "interface_m_a_circle" ],
    [ "MACircleRenderer", "interface_m_a_circle_renderer.html", "interface_m_a_circle_renderer" ],
    [ "MACoordinateBounds", "struct_m_a_coordinate_bounds.html", "struct_m_a_coordinate_bounds" ],
    [ "MACoordinateRegion", "struct_m_a_coordinate_region.html", "struct_m_a_coordinate_region" ],
    [ "MACoordinateSpan", "struct_m_a_coordinate_span.html", "struct_m_a_coordinate_span" ],
    [ "MACustomBuildingOverlay", "interface_m_a_custom_building_overlay.html", "interface_m_a_custom_building_overlay" ],
    [ "MACustomBuildingOverlayOption", "interface_m_a_custom_building_overlay_option.html", "interface_m_a_custom_building_overlay_option" ],
    [ "MACustomBuildingOverlayRenderer", "interface_m_a_custom_building_overlay_renderer.html", "interface_m_a_custom_building_overlay_renderer" ],
    [ "MACustomCalloutView", "interface_m_a_custom_callout_view.html", "interface_m_a_custom_callout_view" ],
    [ "MAGeodesicPolyline", "interface_m_a_geodesic_polyline.html", "interface_m_a_geodesic_polyline" ],
    [ "MAGroundOverlay", "interface_m_a_ground_overlay.html", "interface_m_a_ground_overlay" ],
    [ "MAGroundOverlayRenderer", "interface_m_a_ground_overlay_renderer.html", "interface_m_a_ground_overlay_renderer" ],
    [ "MAHeatMapGradient", "interface_m_a_heat_map_gradient.html", "interface_m_a_heat_map_gradient" ],
    [ "MAHeatMapNode", "interface_m_a_heat_map_node.html", "interface_m_a_heat_map_node" ],
    [ "MAHeatMapTileOverlay", "interface_m_a_heat_map_tile_overlay.html", "interface_m_a_heat_map_tile_overlay" ],
    [ "MAHeatMapVectorItem", "interface_m_a_heat_map_vector_item.html", "interface_m_a_heat_map_vector_item" ],
    [ "MAHeatMapVectorNode", "interface_m_a_heat_map_vector_node.html", "interface_m_a_heat_map_vector_node" ],
    [ "MAHeatMapVectorOverlay", "interface_m_a_heat_map_vector_overlay.html", "interface_m_a_heat_map_vector_overlay" ],
    [ "MAHeatMapVectorOverlayOptions", "interface_m_a_heat_map_vector_overlay_options.html", "interface_m_a_heat_map_vector_overlay_options" ],
    [ "MAHeatMapVectorOverlayRender", "interface_m_a_heat_map_vector_overlay_render.html", "interface_m_a_heat_map_vector_overlay_render" ],
    [ "MAIndoorFloorInfo", "interface_m_a_indoor_floor_info.html", "interface_m_a_indoor_floor_info" ],
    [ "MAIndoorInfo", "interface_m_a_indoor_info.html", "interface_m_a_indoor_info" ],
    [ "MAMapCustomStyleOptions", "interface_m_a_map_custom_style_options.html", "interface_m_a_map_custom_style_options" ],
    [ "MAMapPoint", "struct_m_a_map_point.html", "struct_m_a_map_point" ],
    [ "MAMapRect", "struct_m_a_map_rect.html", "struct_m_a_map_rect" ],
    [ "MAMapSize", "struct_m_a_map_size.html", "struct_m_a_map_size" ],
    [ "MAMapStatus", "interface_m_a_map_status.html", "interface_m_a_map_status" ],
    [ "MAMapView", "interface_m_a_map_view.html", "interface_m_a_map_view" ],
    [ "MAMapView(Annotation)", "category_m_a_map_view_07_annotation_08.html", "category_m_a_map_view_07_annotation_08" ],
    [ "MAMapView(CustomMapStyle)", "category_m_a_map_view_07_custom_map_style_08.html", "category_m_a_map_view_07_custom_map_style_08" ],
    [ "MAMapView(Indoor)", "category_m_a_map_view_07_indoor_08.html", "category_m_a_map_view_07_indoor_08" ],
    [ "MAMapView(Overlay)", "category_m_a_map_view_07_overlay_08.html", "category_m_a_map_view_07_overlay_08" ],
    [ "MAMapView(UserLocation)", "category_m_a_map_view_07_user_location_08.html", "category_m_a_map_view_07_user_location_08" ],
    [ "<MAMapViewDelegate >", "protocol_m_a_map_view_delegate_01-p.html", "protocol_m_a_map_view_delegate_01-p" ],
    [ "MAMultiColoredPolylineRenderer", "interface_m_a_multi_colored_polyline_renderer.html", "interface_m_a_multi_colored_polyline_renderer" ],
    [ "MAMultiPoint", "interface_m_a_multi_point.html", "interface_m_a_multi_point" ],
    [ "MAMultiPointItem", "interface_m_a_multi_point_item.html", "interface_m_a_multi_point_item" ],
    [ "MAMultiPointOverlay", "interface_m_a_multi_point_overlay.html", "interface_m_a_multi_point_overlay" ],
    [ "MAMultiPointOverlayRenderer", "interface_m_a_multi_point_overlay_renderer.html", "interface_m_a_multi_point_overlay_renderer" ],
    [ "<MAMultiPointOverlayRendererDelegate >", "protocol_m_a_multi_point_overlay_renderer_delegate_01-p.html", "protocol_m_a_multi_point_overlay_renderer_delegate_01-p" ],
    [ "MAMultiPolyline", "interface_m_a_multi_polyline.html", "interface_m_a_multi_polyline" ],
    [ "MAMultiTexturePolylineRenderer", "interface_m_a_multi_texture_polyline_renderer.html", "interface_m_a_multi_texture_polyline_renderer" ],
    [ "MAOfflineCity", "interface_m_a_offline_city.html", "interface_m_a_offline_city" ],
    [ "MAOfflineItem", "interface_m_a_offline_item.html", "interface_m_a_offline_item" ],
    [ "MAOfflineItemCommonCity", "interface_m_a_offline_item_common_city.html", "interface_m_a_offline_item_common_city" ],
    [ "MAOfflineItemMunicipality", "interface_m_a_offline_item_municipality.html", null ],
    [ "MAOfflineItemNationWide", "interface_m_a_offline_item_nation_wide.html", null ],
    [ "MAOfflineMap", "interface_m_a_offline_map.html", "interface_m_a_offline_map" ],
    [ "MAOfflineMap(Deprecated)", "category_m_a_offline_map_07_deprecated_08.html", "category_m_a_offline_map_07_deprecated_08" ],
    [ "MAOfflineMapViewController", "interface_m_a_offline_map_view_controller.html", "interface_m_a_offline_map_view_controller" ],
    [ "MAOfflineProvince", "interface_m_a_offline_province.html", "interface_m_a_offline_province" ],
    [ "<MAOverlay >", "protocol_m_a_overlay_01-p.html", "protocol_m_a_overlay_01-p" ],
    [ "MAOverlayPathRenderer", "interface_m_a_overlay_path_renderer.html", "interface_m_a_overlay_path_renderer" ],
    [ "MAOverlayRenderer", "interface_m_a_overlay_renderer.html", "interface_m_a_overlay_renderer" ],
    [ "<MAParticleColorGenerate >", "protocol_m_a_particle_color_generate_01-p.html", "protocol_m_a_particle_color_generate_01-p" ],
    [ "MAParticleConstantRotationGenerate", "interface_m_a_particle_constant_rotation_generate.html", "interface_m_a_particle_constant_rotation_generate" ],
    [ "MAParticleCurveSizeGenerate", "interface_m_a_particle_curve_size_generate.html", "interface_m_a_particle_curve_size_generate" ],
    [ "MAParticleEmissionModule", "interface_m_a_particle_emission_module.html", "interface_m_a_particle_emission_module" ],
    [ "MAParticleOverlay", "interface_m_a_particle_overlay.html", "interface_m_a_particle_overlay" ],
    [ "MAParticleOverlayOptions", "interface_m_a_particle_overlay_options.html", "interface_m_a_particle_overlay_options" ],
    [ "MAParticleOverlayOptionsFactory", "interface_m_a_particle_overlay_options_factory.html", null ],
    [ "MAParticleOverlayRenderer", "interface_m_a_particle_overlay_renderer.html", "interface_m_a_particle_overlay_renderer" ],
    [ "MAParticleOverLifeModule", "interface_m_a_particle_over_life_module.html", "interface_m_a_particle_over_life_module" ],
    [ "MAParticleRandomColorGenerate", "interface_m_a_particle_random_color_generate.html", "interface_m_a_particle_random_color_generate" ],
    [ "MAParticleRandomVelocityGenerate", "interface_m_a_particle_random_velocity_generate.html", "interface_m_a_particle_random_velocity_generate" ],
    [ "MAParticleRectShapeModule", "interface_m_a_particle_rect_shape_module.html", "interface_m_a_particle_rect_shape_module" ],
    [ "<MAParticleRotationGenerate >", "protocol_m_a_particle_rotation_generate_01-p.html", "protocol_m_a_particle_rotation_generate_01-p" ],
    [ "<MAParticleShapeModule >", "protocol_m_a_particle_shape_module_01-p.html", "protocol_m_a_particle_shape_module_01-p" ],
    [ "MAParticleSinglePointShapeModule", "interface_m_a_particle_single_point_shape_module.html", "interface_m_a_particle_single_point_shape_module" ],
    [ "<MAParticleSizeGenerate >", "protocol_m_a_particle_size_generate_01-p.html", "protocol_m_a_particle_size_generate_01-p" ],
    [ "<MAParticleVelocityGenerate >", "protocol_m_a_particle_velocity_generate_01-p.html", "protocol_m_a_particle_velocity_generate_01-p" ],
    [ "MAPathShowRange", "struct_m_a_path_show_range.html", "struct_m_a_path_show_range" ],
    [ "MAPinAnnotationView", "interface_m_a_pin_annotation_view.html", "interface_m_a_pin_annotation_view" ],
    [ "MAPointAnnotation", "interface_m_a_point_annotation.html", "interface_m_a_point_annotation" ],
    [ "MAPolygon", "interface_m_a_polygon.html", "interface_m_a_polygon" ],
    [ "MAPolygonRenderer", "interface_m_a_polygon_renderer.html", "interface_m_a_polygon_renderer" ],
    [ "MAPolyline", "interface_m_a_polyline.html", "interface_m_a_polyline" ],
    [ "MAPolylineRenderer", "interface_m_a_polyline_renderer.html", "interface_m_a_polyline_renderer" ],
    [ "MAShape", "interface_m_a_shape.html", "interface_m_a_shape" ],
    [ "MATileOverlay", "interface_m_a_tile_overlay.html", "interface_m_a_tile_overlay" ],
    [ "MATileOverlay(CustomLoading)", "category_m_a_tile_overlay_07_custom_loading_08.html", "category_m_a_tile_overlay_07_custom_loading_08" ],
    [ "MATileOverlayPath", "struct_m_a_tile_overlay_path.html", "struct_m_a_tile_overlay_path" ],
    [ "MATileOverlayRenderer", "interface_m_a_tile_overlay_renderer.html", "interface_m_a_tile_overlay_renderer" ],
    [ "MATouchPoi", "interface_m_a_touch_poi.html", "interface_m_a_touch_poi" ],
    [ "<MATraceDelegate >", "protocol_m_a_trace_delegate_01-p.html", "protocol_m_a_trace_delegate_01-p" ],
    [ "MATraceLocation", "interface_m_a_trace_location.html", "interface_m_a_trace_location" ],
    [ "MATraceManager", "interface_m_a_trace_manager.html", "interface_m_a_trace_manager" ],
    [ "MATracePoint", "interface_m_a_trace_point.html", "interface_m_a_trace_point" ],
    [ "MAUserLocation", "interface_m_a_user_location.html", "interface_m_a_user_location" ],
    [ "MAUserLocationRepresentation", "interface_m_a_user_location_representation.html", "interface_m_a_user_location_representation" ],
    [ "NSValue(NSValueMAGeometryExtensions)", "category_n_s_value_07_n_s_value_m_a_geometry_extensions_08.html", "category_n_s_value_07_n_s_value_m_a_geometry_extensions_08" ]
];