var _a_map_search_obj_8h =
[
    [ "AMapPOISearchBaseRequest", "interface_a_map_p_o_i_search_base_request.html", "interface_a_map_p_o_i_search_base_request" ],
    [ "AMapPOIIDSearchRequest", "interface_a_map_p_o_i_i_d_search_request.html", "interface_a_map_p_o_i_i_d_search_request" ],
    [ "AMapPOIKeywordsSearchRequest", "interface_a_map_p_o_i_keywords_search_request.html", "interface_a_map_p_o_i_keywords_search_request" ],
    [ "AMapPOIAroundSearchRequest", "interface_a_map_p_o_i_around_search_request.html", "interface_a_map_p_o_i_around_search_request" ],
    [ "AMapPOIPolygonSearchRequest", "interface_a_map_p_o_i_polygon_search_request.html", "interface_a_map_p_o_i_polygon_search_request" ],
    [ "AMapPOISearchResponse", "interface_a_map_p_o_i_search_response.html", "interface_a_map_p_o_i_search_response" ],
    [ "AMapRoutePOISearchRequest", "interface_a_map_route_p_o_i_search_request.html", "interface_a_map_route_p_o_i_search_request" ],
    [ "AMapRoutePOISearchResponse", "interface_a_map_route_p_o_i_search_response.html", "interface_a_map_route_p_o_i_search_response" ],
    [ "AMapInputTipsSearchRequest", "interface_a_map_input_tips_search_request.html", "interface_a_map_input_tips_search_request" ],
    [ "AMapInputTipsSearchResponse", "interface_a_map_input_tips_search_response.html", "interface_a_map_input_tips_search_response" ],
    [ "AMapGeocodeSearchRequest", "interface_a_map_geocode_search_request.html", "interface_a_map_geocode_search_request" ],
    [ "AMapGeocodeSearchResponse", "interface_a_map_geocode_search_response.html", "interface_a_map_geocode_search_response" ],
    [ "AMapReGeocodeSearchRequest", "interface_a_map_re_geocode_search_request.html", "interface_a_map_re_geocode_search_request" ],
    [ "AMapReGeocodeSearchResponse", "interface_a_map_re_geocode_search_response.html", "interface_a_map_re_geocode_search_response" ],
    [ "AMapBusStopSearchRequest", "interface_a_map_bus_stop_search_request.html", "interface_a_map_bus_stop_search_request" ],
    [ "AMapBusStopSearchResponse", "interface_a_map_bus_stop_search_response.html", "interface_a_map_bus_stop_search_response" ],
    [ "AMapBusLineBaseSearchRequest", "interface_a_map_bus_line_base_search_request.html", "interface_a_map_bus_line_base_search_request" ],
    [ "AMapBusLineNameSearchRequest", "interface_a_map_bus_line_name_search_request.html", "interface_a_map_bus_line_name_search_request" ],
    [ "AMapBusLineIDSearchRequest", "interface_a_map_bus_line_i_d_search_request.html", "interface_a_map_bus_line_i_d_search_request" ],
    [ "AMapBusLineSearchResponse", "interface_a_map_bus_line_search_response.html", "interface_a_map_bus_line_search_response" ],
    [ "AMapDistrictSearchRequest", "interface_a_map_district_search_request.html", "interface_a_map_district_search_request" ],
    [ "AMapDistrictSearchResponse", "interface_a_map_district_search_response.html", "interface_a_map_district_search_response" ],
    [ "AMapRouteSearchBaseRequest", "interface_a_map_route_search_base_request.html", "interface_a_map_route_search_base_request" ],
    [ "AMapDrivingRouteSearchRequest", "interface_a_map_driving_route_search_request.html", "interface_a_map_driving_route_search_request" ],
    [ "AMapWalkingRouteSearchRequest", "interface_a_map_walking_route_search_request.html", "interface_a_map_walking_route_search_request" ],
    [ "AMapTransitRouteSearchRequest", "interface_a_map_transit_route_search_request.html", "interface_a_map_transit_route_search_request" ],
    [ "AMapRidingRouteSearchRequest", "interface_a_map_riding_route_search_request.html", "interface_a_map_riding_route_search_request" ],
    [ "AMapRouteSearchResponse", "interface_a_map_route_search_response.html", "interface_a_map_route_search_response" ],
    [ "AMapRidingRouteSearchResponse", "interface_a_map_riding_route_search_response.html", null ],
    [ "AMapTruckRouteSearchRequest", "interface_a_map_truck_route_search_request.html", "interface_a_map_truck_route_search_request" ],
    [ "AMapDistanceSearchRequest", "interface_a_map_distance_search_request.html", "interface_a_map_distance_search_request" ],
    [ "AMapDistanceSearchResponse", "interface_a_map_distance_search_response.html", "interface_a_map_distance_search_response" ],
    [ "AMapWeatherSearchRequest", "interface_a_map_weather_search_request.html", "interface_a_map_weather_search_request" ],
    [ "AMapWeatherSearchResponse", "interface_a_map_weather_search_response.html", "interface_a_map_weather_search_response" ],
    [ "AMapRoadTrafficSearchBaseRequest", "interface_a_map_road_traffic_search_base_request.html", "interface_a_map_road_traffic_search_base_request" ],
    [ "AMapRoadTrafficSearchRequest", "interface_a_map_road_traffic_search_request.html", "interface_a_map_road_traffic_search_request" ],
    [ "AMapRoadTrafficCircleSearchRequest", "interface_a_map_road_traffic_circle_search_request.html", "interface_a_map_road_traffic_circle_search_request" ],
    [ "AMapRoadTrafficSearchResponse", "interface_a_map_road_traffic_search_response.html", "interface_a_map_road_traffic_search_response" ],
    [ "AMapNearbySearchRequest", "interface_a_map_nearby_search_request.html", "interface_a_map_nearby_search_request" ],
    [ "AMapNearbySearchResponse", "interface_a_map_nearby_search_response.html", "interface_a_map_nearby_search_response" ],
    [ "AMapCloudSearchBaseRequest", "interface_a_map_cloud_search_base_request.html", "interface_a_map_cloud_search_base_request" ],
    [ "AMapCloudPOIAroundSearchRequest", "interface_a_map_cloud_p_o_i_around_search_request.html", "interface_a_map_cloud_p_o_i_around_search_request" ],
    [ "AMapCloudPOIPolygonSearchRequest", "interface_a_map_cloud_p_o_i_polygon_search_request.html", "interface_a_map_cloud_p_o_i_polygon_search_request" ],
    [ "AMapCloudPOIIDSearchRequest", "interface_a_map_cloud_p_o_i_i_d_search_request.html", "interface_a_map_cloud_p_o_i_i_d_search_request" ],
    [ "AMapCloudPOILocalSearchRequest", "interface_a_map_cloud_p_o_i_local_search_request.html", "interface_a_map_cloud_p_o_i_local_search_request" ],
    [ "AMapCloudPOISearchResponse", "interface_a_map_cloud_p_o_i_search_response.html", "interface_a_map_cloud_p_o_i_search_response" ],
    [ "AMapShareSearchBaseRequest", "interface_a_map_share_search_base_request.html", null ],
    [ "AMapLocationShareSearchRequest", "interface_a_map_location_share_search_request.html", "interface_a_map_location_share_search_request" ],
    [ "AMapPOIShareSearchRequest", "interface_a_map_p_o_i_share_search_request.html", "interface_a_map_p_o_i_share_search_request" ],
    [ "AMapRouteShareSearchRequest", "interface_a_map_route_share_search_request.html", "interface_a_map_route_share_search_request" ],
    [ "AMapNavigationShareSearchRequest", "interface_a_map_navigation_share_search_request.html", "interface_a_map_navigation_share_search_request" ],
    [ "AMapShareSearchResponse", "interface_a_map_share_search_response.html", "interface_a_map_share_search_response" ],
    [ "AMapFutureRouteSearchRequest", "interface_a_map_future_route_search_request.html", "interface_a_map_future_route_search_request" ],
    [ "AMapFutureRouteSearchResponse", "interface_a_map_future_route_search_response.html", "interface_a_map_future_route_search_response" ],
    [ "AMapCloudSortType", "_a_map_search_obj_8h.html#ae1007fb1219f2262934174292a0137b0", [
      [ "AMapCloudSortTypeDESC", "_a_map_search_obj_8h.html#ae1007fb1219f2262934174292a0137b0a1a2698ef92529fbc88370158c0dee0a4", null ],
      [ "AMapCloudSortTypeASC", "_a_map_search_obj_8h.html#ae1007fb1219f2262934174292a0137b0ad284cf562ded54c2f9a6470baf895754", null ]
    ] ],
    [ "AMapDrivingRouteExcludeType", "_a_map_search_obj_8h.html#afff2aadc91c1b02b9fd7de0dbf6e04d0", [
      [ "AMapDrivingRouteExcludeTypeNone", "_a_map_search_obj_8h.html#afff2aadc91c1b02b9fd7de0dbf6e04d0a38847d059715240f0d95d69f09662227", null ],
      [ "AMapDrivingRouteExcludeTypeToll", "_a_map_search_obj_8h.html#afff2aadc91c1b02b9fd7de0dbf6e04d0a797b6ad2c00894ef606c15307eaf510a", null ],
      [ "AMapDrivingRouteExcludeTypeMotorway", "_a_map_search_obj_8h.html#afff2aadc91c1b02b9fd7de0dbf6e04d0a060dc7af94efe15e59295843636ccbd4", null ],
      [ "AMapDrivingRouteExcludeTypeFerry", "_a_map_search_obj_8h.html#afff2aadc91c1b02b9fd7de0dbf6e04d0aef6669509f9eac56f2963bece2782935", null ]
    ] ],
    [ "AMapNearbySearchType", "_a_map_search_obj_8h.html#ad58bd0bdde28de565e849d922d955b4e", [
      [ "AMapNearbySearchTypeLiner", "_a_map_search_obj_8h.html#ad58bd0bdde28de565e849d922d955b4ea4efd4aa1316058b1d6c538e48541b758", null ],
      [ "AMapNearbySearchTypeDriving", "_a_map_search_obj_8h.html#ad58bd0bdde28de565e849d922d955b4eaf283fc876cc41324dcdbfd5670c9be00", null ]
    ] ],
    [ "AMapRoutePOISearchType", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64", [
      [ "AMapRoutePOISearchTypeGasStation", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64a38361e4ce256e15c77aef8fc10f19d5d", null ],
      [ "AMapRoutePOISearchTypeMaintenanceStation", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64a49b8cae32dde595ef6074994390194c5", null ],
      [ "AMapRoutePOISearchTypeATM", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64aca3fe124e47f353d820e44740d933bf4", null ],
      [ "AMapRoutePOISearchTypeToilet", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64acb5651535b454c8674a658ac4b2456e2", null ],
      [ "AMapRoutePOISearchTypeGasAirStation", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64aec20265db21125ebe61753be8ebe8cc3", null ],
      [ "AMapRoutePOISearchTypeParkStation", "_a_map_search_obj_8h.html#ace7f5fe6f2655fddfc82c1aa7e647e64a60e0fa48a97f2cdaca98fe12e086ea5a", null ]
    ] ],
    [ "AMapTruckSizeType", "_a_map_search_obj_8h.html#a6c90093d02f7ea4ad2a9ae6285ca7412", [
      [ "AMapTruckSizeTypeMini", "_a_map_search_obj_8h.html#a6c90093d02f7ea4ad2a9ae6285ca7412a32270ca1d30a2106dafaee5d0f515991", null ],
      [ "AMapTruckSizeTypeLight", "_a_map_search_obj_8h.html#a6c90093d02f7ea4ad2a9ae6285ca7412ada47b1a2db6b9ce41f387a9ac29b7e86", null ],
      [ "AMapTruckSizeTypeMedium", "_a_map_search_obj_8h.html#a6c90093d02f7ea4ad2a9ae6285ca7412acaba12c5b10b6faa98cf6a1a8aad32e7", null ],
      [ "AMapTruckSizeTypeHeavy", "_a_map_search_obj_8h.html#a6c90093d02f7ea4ad2a9ae6285ca7412a6a917c031250dae65e5aab1b1ecf2879", null ]
    ] ],
    [ "AMapWeatherType", "_a_map_search_obj_8h.html#a52e12e9f15f8c0a28559d1f74ba328d4", [
      [ "AMapWeatherTypeLive", "_a_map_search_obj_8h.html#a52e12e9f15f8c0a28559d1f74ba328d4a2097bb45ddcfd685d7412661937393c6", null ],
      [ "AMapWeatherTypeForecast", "_a_map_search_obj_8h.html#a52e12e9f15f8c0a28559d1f74ba328d4ad6b8218aa350b17f6ecd3fc849a271e2", null ]
    ] ]
];