var files =
[
    [ "AMapCommonObj.h", "_a_map_common_obj_8h.html", [
      [ "AMapSearchObject", "interface_a_map_search_object.html", "interface_a_map_search_object" ],
      [ "AMapGeoPoint", "interface_a_map_geo_point.html", "interface_a_map_geo_point" ],
      [ "AMapGeoPolygon", "interface_a_map_geo_polygon.html", "interface_a_map_geo_polygon" ],
      [ "AMapCity", "interface_a_map_city.html", "interface_a_map_city" ],
      [ "AMapSuggestion", "interface_a_map_suggestion.html", "interface_a_map_suggestion" ],
      [ "AMapTip", "interface_a_map_tip.html", "interface_a_map_tip" ],
      [ "AMapImage", "interface_a_map_image.html", "interface_a_map_image" ],
      [ "AMapPOIExtension", "interface_a_map_p_o_i_extension.html", "interface_a_map_p_o_i_extension" ],
      [ "AMapIndoorData", "interface_a_map_indoor_data.html", "interface_a_map_indoor_data" ],
      [ "AMapSubPOI", "interface_a_map_sub_p_o_i.html", "interface_a_map_sub_p_o_i" ],
      [ "AMapRoutePOI", "interface_a_map_route_p_o_i.html", "interface_a_map_route_p_o_i" ],
      [ "AMapPOI", "interface_a_map_p_o_i.html", "interface_a_map_p_o_i" ],
      [ "AMapAOI", "interface_a_map_a_o_i.html", "interface_a_map_a_o_i" ],
      [ "AMapRoad", "interface_a_map_road.html", "interface_a_map_road" ],
      [ "AMapRoadInter", "interface_a_map_road_inter.html", "interface_a_map_road_inter" ],
      [ "AMapStreetNumber", "interface_a_map_street_number.html", "interface_a_map_street_number" ],
      [ "AMapBusinessArea", "interface_a_map_business_area.html", "interface_a_map_business_area" ],
      [ "AMapAddressComponent", "interface_a_map_address_component.html", "interface_a_map_address_component" ],
      [ "AMapReGeocode", "interface_a_map_re_geocode.html", "interface_a_map_re_geocode" ],
      [ "AMapGeocode", "interface_a_map_geocode.html", "interface_a_map_geocode" ],
      [ "AMapBusStop", "interface_a_map_bus_stop.html", "interface_a_map_bus_stop" ],
      [ "AMapBusLine", "interface_a_map_bus_line.html", "interface_a_map_bus_line" ],
      [ "AMapDistrict", "interface_a_map_district.html", "interface_a_map_district" ],
      [ "AMapTMC", "interface_a_map_t_m_c.html", "interface_a_map_t_m_c" ],
      [ "AMapStep", "interface_a_map_step.html", "interface_a_map_step" ],
      [ "AMapPath", "interface_a_map_path.html", "interface_a_map_path" ],
      [ "AMapFutureTimeInfoElement", "interface_a_map_future_time_info_element.html", "interface_a_map_future_time_info_element" ],
      [ "AMapFutureTimeInfo", "interface_a_map_future_time_info.html", "interface_a_map_future_time_info" ],
      [ "AMapWalking", "interface_a_map_walking.html", "interface_a_map_walking" ],
      [ "AMapTaxi", "interface_a_map_taxi.html", "interface_a_map_taxi" ],
      [ "AMapRailwayStation", "interface_a_map_railway_station.html", "interface_a_map_railway_station" ],
      [ "AMapRailwaySpace", "interface_a_map_railway_space.html", "interface_a_map_railway_space" ],
      [ "AMapRailway", "interface_a_map_railway.html", "interface_a_map_railway" ],
      [ "AMapSegment", "interface_a_map_segment.html", "interface_a_map_segment" ],
      [ "AMapTransit", "interface_a_map_transit.html", "interface_a_map_transit" ],
      [ "AMapRoute", "interface_a_map_route.html", "interface_a_map_route" ],
      [ "AMapDistanceResult", "interface_a_map_distance_result.html", "interface_a_map_distance_result" ],
      [ "AMapLocalWeatherLive", "interface_a_map_local_weather_live.html", "interface_a_map_local_weather_live" ],
      [ "AMapLocalDayWeatherForecast", "interface_a_map_local_day_weather_forecast.html", "interface_a_map_local_day_weather_forecast" ],
      [ "AMapLocalWeatherForecast", "interface_a_map_local_weather_forecast.html", "interface_a_map_local_weather_forecast" ],
      [ "AMapNearbyUserInfo", "interface_a_map_nearby_user_info.html", "interface_a_map_nearby_user_info" ],
      [ "AMapTrafficEvaluation", "interface_a_map_traffic_evaluation.html", "interface_a_map_traffic_evaluation" ],
      [ "AMapTrafficRoad", "interface_a_map_traffic_road.html", "interface_a_map_traffic_road" ],
      [ "AMapTrafficInfo", "interface_a_map_traffic_info.html", "interface_a_map_traffic_info" ],
      [ "AMapCloudImage", "interface_a_map_cloud_image.html", "interface_a_map_cloud_image" ],
      [ "AMapCloudPOI", "interface_a_map_cloud_p_o_i.html", "interface_a_map_cloud_p_o_i" ]
    ] ],
    [ "AMapNearbySearchManager.h", "_a_map_nearby_search_manager_8h.html", [
      [ "<AMapNearbySearchManagerDelegate >", "protocol_a_map_nearby_search_manager_delegate_01-p.html", "protocol_a_map_nearby_search_manager_delegate_01-p" ],
      [ "AMapNearbySearchManager", "interface_a_map_nearby_search_manager.html", "interface_a_map_nearby_search_manager" ]
    ] ],
    [ "AMapNearbyUploadInfo.h", "_a_map_nearby_upload_info_8h.html", "_a_map_nearby_upload_info_8h" ],
    [ "AMapSearchAPI.h", "_a_map_search_a_p_i_8h.html", "_a_map_search_a_p_i_8h" ],
    [ "AMapSearchError.h", "_a_map_search_error_8h.html", "_a_map_search_error_8h" ],
    [ "AMapSearchKit.h", "_a_map_search_kit_8h.html", null ],
    [ "AMapSearchObj.h", "_a_map_search_obj_8h.html", "_a_map_search_obj_8h" ],
    [ "AMapSearchVersion.h", "_a_map_search_version_8h.html", "_a_map_search_version_8h" ]
];